### ISSUE TITLE
metacatalog/data folder is not installed with metacatalog

### ISSUE THREAD

**Issue by AlexDo1** [VForWaTer/metacatalog#109] opened 2021-01-10 12:31 UTC
The data folder is missing when installing metacatalog which leads to an error when running the init command.

![image](https://user-images.githubusercontent.com/23619690/104122885-f1d53f80-5347-11eb-9268-1594fc604388.png)

**Comment by mmaelicke** [comment] 2021-01-10 16:52
I think I know what the problem is... I'll try to fix

**Comment by mmaelicke** [comment] 2021-01-11 10:13
This issue will take a bit longer than expected. @AlexDo1 hold tight until this evening or tomorrow....

**Comment by mmaelicke** [comment] 2021-01-11 13:18
@AlexDo1 I just released `metacatalog 0.2.7`, which should fix this problem. Can you verify, and close the issue if solved?

**Comment by AlexDo1** [comment] 2021-01-11 17:35
It works now, nice!

**Closed** 2021-01-12 06:47 UTC
Labels: bug
